import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface Song {
    id: string;
    title: string;
    originalUrl: string;
    duration: number;
    size: number;
    dateAdded: number;
    playCount: number;
    thumbnail?: string;
    artist?: string;
}

export interface Playlist {
    id: string;
    name: string;
    songIds: string[];
    isAutoGenerated: boolean;
    createdAt: number;
}

interface LibraryState {
    songs: Record<string, Song>;
    playlists: Record<string, Playlist>;

    // Actions
    addSong: (song: Song) => void;
    removeSong: (id: string) => void;
    updatePlayCount: (id: string) => void;

    createPlaylist: (name: string) => void;
    deletePlaylist: (id: string) => void;
    renamePlaylist: (id: string, newName: string) => void;
    addSongToPlaylist: (playlistId: string, songId: string) => void;
    removeSongFromPlaylist: (playlistId: string, songId: string) => void;
}

export const useLibraryStore = create<LibraryState>()(
    persist(
        (set) => ({
            songs: {},
            playlists: {
                'favorites': { id: 'favorites', name: 'Favorites', songIds: [], isAutoGenerated: true, createdAt: Date.now() },
                'recently-added': { id: 'recently-added', name: 'Recently Added', songIds: [], isAutoGenerated: true, createdAt: Date.now() },
                'most-played': { id: 'most-played', name: 'Most Played', songIds: [], isAutoGenerated: true, createdAt: Date.now() }
            },

            addSong: (song) => set((state) => {
                // Automatically add to Recently Added
                const recentlyAdded = { ...state.playlists['recently-added'] };
                recentlyAdded.songIds = [song.id, ...recentlyAdded.songIds.filter(id => id !== song.id)];

                return {
                    songs: { ...state.songs, [song.id]: song },
                    playlists: { ...state.playlists, 'recently-added': recentlyAdded }
                };
            }),

            removeSong: (id) => set((state) => {
                const newSongs = { ...state.songs };
                delete newSongs[id];

                // Remove from all playlists
                const newPlaylists = { ...state.playlists };
                Object.keys(newPlaylists).forEach(pId => {
                    newPlaylists[pId].songIds = newPlaylists[pId].songIds.filter(sId => sId !== id);
                });

                return { songs: newSongs, playlists: newPlaylists };
            }),

            updatePlayCount: (id) => set((state) => {
                const song = state.songs[id];
                if (!song) return state;

                const newSongs = { ...state.songs, [id]: { ...song, playCount: song.playCount + 1 } };

                // Compute Most Played
                const allSongs = Object.values(newSongs).sort((a, b) => b.playCount - a.playCount);
                const mostPlayed = { ...state.playlists['most-played'], songIds: allSongs.filter(s => s.playCount > 0).slice(0, 50).map(s => s.id) };

                return {
                    songs: newSongs,
                    playlists: { ...state.playlists, 'most-played': mostPlayed }
                };
            }),

            createPlaylist: (name) => set((state) => {
                const id = `playlist_${Date.now()}`;
                return {
                    playlists: {
                        ...state.playlists,
                        [id]: { id, name, songIds: [], isAutoGenerated: false, createdAt: Date.now() }
                    }
                };
            }),

            deletePlaylist: (id) => set((state) => {
                if (state.playlists[id]?.isAutoGenerated) return state; // Don't delete system playlists
                const newPlaylists = { ...state.playlists };
                delete newPlaylists[id];
                return { playlists: newPlaylists };
            }),

            renamePlaylist: (id, newName) => set((state) => {
                if (state.playlists[id]?.isAutoGenerated) return state;
                return {
                    playlists: {
                        ...state.playlists,
                        [id]: { ...state.playlists[id], name: newName }
                    }
                };
            }),

            addSongToPlaylist: (playlistId, songId) => set((state) => {
                const playlist = state.playlists[playlistId];
                if (!playlist || playlist.songIds.includes(songId)) return state;

                return {
                    playlists: {
                        ...state.playlists,
                        [playlistId]: { ...playlist, songIds: [...playlist.songIds, songId] }
                    }
                };
            }),

            removeSongFromPlaylist: (playlistId, songId) => set((state) => {
                const playlist = state.playlists[playlistId];
                if (!playlist) return state;

                return {
                    playlists: {
                        ...state.playlists,
                        [playlistId]: { ...playlist, songIds: playlist.songIds.filter(id => id !== songId) }
                    }
                };
            }),

            getTotalStorageSize: () => {
                const { songs } = useLibraryStore.getState();
                return Object.values(songs).reduce((total, song) => total + (song.size || 0), 0);
            },
        }),
        {
            name: 'anti-gravity-library-storage',
        }
    )
);
