import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLibraryStore } from '../store/libraryStore';
import { usePlayerStore } from '../store/playerStore';
import { Play, Plus, Trash2, ListMusic, LayoutGrid, List, MoreVertical, ChevronLeft } from 'lucide-react';
import PageTransition from '../components/layout/PageTransition';

const Playlists: React.FC = () => {
    const navigate = useNavigate();
    const { playlists, songs, createPlaylist, deletePlaylist, removeSongFromPlaylist, addSongToPlaylist } = useLibraryStore();
    const { playSong, currentSongId, queue, setQueue } = usePlayerStore();

    const [activePlaylistId, setActivePlaylistId] = useState<string | null>(null);
    const [newPlaylistName, setNewPlaylistName] = useState('');
    const [isCreating, setIsCreating] = useState(false);
    const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
    const [menuOpenId, setMenuOpenId] = useState<string | null>(null);
    const [playlistModalSongId, setPlaylistModalSongId] = useState<string | null>(null);

    const handleCreate = (e: React.FormEvent) => {
        e.preventDefault();
        if (newPlaylistName.trim()) {
            createPlaylist(newPlaylistName.trim());
            setNewPlaylistName('');
            setIsCreating(false);
        }
    };

    const handlePlayPlaylist = (playlistId: string) => {
        const playlist = playlists[playlistId];
        if (playlist && playlist.songIds.length > 0) {
            playSong(playlist.songIds[0], playlist.songIds);
        }
    };

    const activePlaylist = activePlaylistId ? playlists[activePlaylistId] : null;

    return (
        <PageTransition>
            <div className="w-full h-full flex flex-col pb-10 max-w-4xl mx-auto">
                {/* Detail View */}
                {activePlaylist ? (
                    <div>
                        <button onClick={() => setActivePlaylistId(null)} className="flex items-center gap-1 text-zinc-500 hover:text-white mb-6 text-sm font-medium tracking-wide transition-colors">
                            <ChevronLeft size={16} /> Back
                        </button>

                        <div className="flex items-end justify-between mb-6 gap-4 flex-wrap">
                            <div>
                                <h2 className="text-2xl md:text-4xl font-black italic tracking-tight text-white font-['Outfit'] mb-1">{activePlaylist.name}</h2>
                                <p className="text-zinc-500 text-sm tracking-wide">
                                    {activePlaylist.isAutoGenerated ? 'System Playlist' : 'Custom Playlist'} • {activePlaylist.songIds.length} tracks
                                </p>
                            </div>

                            <div className="flex items-center gap-3">
                                <div className="flex gap-0.5 bg-white/3 rounded-lg p-0.5 border border-white/5">
                                    <button onClick={() => setViewMode('grid')} className={`p-1.5 rounded-md transition-colors ${viewMode === 'grid' ? 'bg-white/10 text-white' : 'text-zinc-600'}`}>
                                        <LayoutGrid size={14} />
                                    </button>
                                    <button onClick={() => setViewMode('list')} className={`p-1.5 rounded-md transition-colors ${viewMode === 'list' ? 'bg-white/10 text-white' : 'text-zinc-600'}`}>
                                        <List size={14} />
                                    </button>
                                </div>

                                <button
                                    onClick={() => handlePlayPlaylist(activePlaylist.id)}
                                    disabled={activePlaylist.songIds.length === 0}
                                    className="px-6 py-2.5 rounded-xl font-bold text-sm bg-accent text-black hover:bg-[#E5C348] transition-all shadow-[0_0_15px_rgba(212,175,55,0.3)] tracking-wider flex items-center gap-2 disabled:opacity-50"
                                >
                                    <Play size={16} fill="currentColor" /> PLAY ALL
                                </button>
                            </div>
                        </div>

                        {activePlaylist.songIds.length === 0 ? (
                            <div className="text-center py-16 glass-panel rounded-2xl">
                                <p className="text-zinc-500 text-sm">This playlist is empty</p>
                            </div>
                        ) : viewMode === 'grid' ? (
                            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
                                {activePlaylist.songIds.map((songId, index) => {
                                    const song = songs[songId];
                                    if (!song) return null;
                                    const thumb = song.thumbnail || `https://picsum.photos/seed/${songId}/400/400`;

                                    return (
                                        <div
                                            key={`${songId}-${index}`}
                                            onDoubleClick={() => { if (currentSongId !== songId) playSong(songId, activePlaylist.songIds); navigate('/now-playing'); }}
                                            className="relative group rounded-2xl overflow-hidden bg-surface border border-white/5 hover:border-white/10 transition-all"
                                        >
                                            <div className="aspect-square bg-zinc-900 relative">
                                                <img src={thumb} alt={song.title} className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity" />
                                                <div
                                                    className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center cursor-pointer"
                                                    onClick={() => playSong(songId, activePlaylist.songIds)}
                                                >
                                                    <div className="w-11 h-11 bg-accent rounded-full flex items-center justify-center text-black shadow-[0_0_15px_rgba(212,175,55,0.5)] scale-75 group-hover:scale-100 transition-transform">
                                                        <Play size={18} className="ml-0.5" fill="currentColor" />
                                                    </div>
                                                </div>

                                                <button
                                                    onClick={(e) => { e.stopPropagation(); setMenuOpenId(menuOpenId === songId ? null : songId); }}
                                                    className="absolute top-2 right-2 p-1.5 bg-black/60 text-zinc-400 hover:text-white opacity-0 group-hover:opacity-100 transition-all rounded-full z-10"
                                                >
                                                    <MoreVertical size={12} />
                                                </button>

                                                {menuOpenId === songId && (
                                                    <div className="absolute top-10 right-2 bg-surface border border-white/10 rounded-xl p-1.5 min-w-[140px] shadow-2xl z-50" onClick={(e) => e.stopPropagation()}>
                                                        <button onClick={() => { if (!queue.includes(songId)) setQueue([...queue, songId]); setMenuOpenId(null); }}
                                                            className="w-full text-left px-3 py-2 rounded-lg text-xs text-zinc-300 hover:bg-white/5">Add to Queue</button>
                                                        <button onClick={() => { setPlaylistModalSongId(songId); setMenuOpenId(null); }}
                                                            className="w-full text-left px-3 py-2 rounded-lg text-xs text-zinc-300 hover:bg-white/5">Add to Playlist</button>
                                                        {!activePlaylist.isAutoGenerated && (
                                                            <>
                                                                <div className="h-px bg-white/5 my-1 mx-2" />
                                                                <button onClick={() => { removeSongFromPlaylist(activePlaylist.id, songId); setMenuOpenId(null); }}
                                                                    className="w-full text-left px-3 py-2 rounded-lg text-xs text-red-400 hover:bg-red-400/10">Remove</button>
                                                            </>
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                            <div className="p-3">
                                                <p className="font-semibold text-zinc-200 text-sm truncate">{song.title}</p>
                                                <p className="text-zinc-600 text-xs truncate mt-0.5">{song.artist || 'Local Audio'}</p>
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        ) : (
                            <div className="flex flex-col gap-1.5">
                                {activePlaylist.songIds.map((songId, index) => {
                                    const song = songs[songId];
                                    if (!song) return null;
                                    const thumb = song.thumbnail || `https://picsum.photos/seed/${songId}/100/100`;

                                    return (
                                        <div
                                            key={`${songId}-${index}`}
                                            onDoubleClick={() => { if (currentSongId !== songId) playSong(songId, activePlaylist.songIds); navigate('/now-playing'); }}
                                            className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-white/3 transition-colors group border border-transparent"
                                        >
                                            <div className="relative w-11 h-11 rounded-lg overflow-hidden shrink-0">
                                                <img src={thumb} alt={song.title} className="w-full h-full object-cover" />
                                                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center cursor-pointer transition-opacity"
                                                    onClick={() => playSong(songId, activePlaylist.songIds)}>
                                                    <Play size={14} fill="white" className="text-white ml-0.5" />
                                                </div>
                                            </div>
                                            <div className="flex-1 min-w-0">
                                                <h4 className="text-zinc-200 font-medium text-sm truncate">{song.title}</h4>
                                                <p className="text-zinc-600 text-xs truncate">{song.artist || 'Local Audio'}</p>
                                            </div>
                                            <div className="relative">
                                                <button onClick={(e) => { e.stopPropagation(); setMenuOpenId(menuOpenId === songId ? null : songId); }}
                                                    className="p-2 text-zinc-600 hover:text-white rounded-full hover:bg-white/5 opacity-0 group-hover:opacity-100 transition-opacity">
                                                    <MoreVertical size={14} />
                                                </button>
                                                {menuOpenId === songId && (
                                                    <div className="absolute top-10 right-0 bg-surface border border-white/10 rounded-xl p-1.5 min-w-[140px] shadow-2xl z-50" onClick={(e) => e.stopPropagation()}>
                                                        <button onClick={() => { if (!queue.includes(songId)) setQueue([...queue, songId]); setMenuOpenId(null); }}
                                                            className="w-full text-left px-3 py-2 rounded-lg text-xs text-zinc-300 hover:bg-white/5">Add to Queue</button>
                                                        <button onClick={() => { setPlaylistModalSongId(songId); setMenuOpenId(null); }}
                                                            className="w-full text-left px-3 py-2 rounded-lg text-xs text-zinc-300 hover:bg-white/5">Add to Playlist</button>
                                                        {!activePlaylist.isAutoGenerated && (
                                                            <>
                                                                <div className="h-px bg-white/5 my-1 mx-2" />
                                                                <button onClick={() => { removeSongFromPlaylist(activePlaylist.id, songId); setMenuOpenId(null); }}
                                                                    className="w-full text-left px-3 py-2 rounded-lg text-xs text-red-400 hover:bg-red-400/10">Remove</button>
                                                            </>
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        )}
                    </div>
                ) : (
                    /* Playlist List */
                    <div>
                        <div className="flex items-end justify-between mb-6">
                            <div>
                                <h2 className="text-4xl md:text-5xl font-black italic tracking-tighter text-white/5 font-['Outfit'] leading-none select-none">
                                    PLAYLISTS
                                </h2>
                                <h3 className="text-lg font-bold tracking-wide text-white -mt-5 md:-mt-6 ml-1 font-['Outfit']">
                                    Your <span className="text-accent">Playlists</span>
                                </h3>
                            </div>
                            <button
                                onClick={() => setIsCreating(!isCreating)}
                                className="px-5 py-2.5 rounded-xl font-bold text-sm bg-accent/10 text-accent border border-accent/20 hover:bg-accent/20 transition-all tracking-wider flex items-center gap-2"
                            >
                                {isCreating ? 'CANCEL' : <><Plus size={16} /> NEW</>}
                            </button>
                        </div>

                        {isCreating && (
                            <form onSubmit={handleCreate} className="mb-6 p-4 glass-panel rounded-2xl flex gap-3">
                                <input
                                    autoFocus
                                    type="text"
                                    value={newPlaylistName}
                                    onChange={(e) => setNewPlaylistName(e.target.value)}
                                    placeholder="Playlist name..."
                                    className="flex-1 bg-black/40 border border-white/5 rounded-xl px-4 py-3 text-white text-sm focus:outline-none focus:border-accent/30 transition-colors"
                                />
                                <button type="submit" disabled={!newPlaylistName.trim()} className="px-5 rounded-xl font-bold text-sm bg-accent text-black hover:bg-[#E5C348] disabled:opacity-50 transition-colors">
                                    CREATE
                                </button>
                            </form>
                        )}

                        <div className="flex flex-col gap-2">
                            {Object.values(playlists).sort((a, b) => b.createdAt - a.createdAt).map((playlist) => (
                                <div key={playlist.id} className="flex items-center gap-4 p-3 rounded-2xl hover:bg-white/3 transition-all group relative border border-transparent cursor-pointer"
                                    onClick={() => setActivePlaylistId(playlist.id)}>

                                    <div className={`w-14 h-14 md:w-16 md:h-16 shrink-0 rounded-xl flex items-center justify-center overflow-hidden ${playlist.isAutoGenerated ? 'bg-linear-to-br from-accent/20 to-accent/5 border border-accent/10' : 'bg-white/3 border border-white/5'}`}>
                                        <ListMusic size={22} className={playlist.isAutoGenerated ? 'text-accent/60' : 'text-zinc-600'} />
                                    </div>

                                    <div className="flex-1 min-w-0">
                                        <h3 className="text-white font-semibold text-sm truncate group-hover:text-accent transition-colors">{playlist.name}</h3>
                                        <p className="text-zinc-600 text-xs mt-0.5">{playlist.songIds.length} tracks</p>
                                    </div>

                                    {!playlist.isAutoGenerated && (
                                        <button
                                            onClick={(e) => { e.stopPropagation(); deletePlaylist(playlist.id); }}
                                            className="p-2 rounded-full text-zinc-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity"
                                        >
                                            <Trash2 size={16} />
                                        </button>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>

            {/* Playlist Modal */}
            {playlistModalSongId && (
                <div className="fixed inset-0 z-100 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm" onClick={() => setPlaylistModalSongId(null)}>
                    <div className="bg-surface border border-white/10 rounded-3xl p-6 w-full max-w-sm" onClick={e => e.stopPropagation()}>
                        <h3 className="text-lg font-bold text-white mb-4 font-['Outfit']">Add to Playlist</h3>
                        <div className="space-y-2 max-h-[60vh] overflow-y-auto">
                            {Object.values(playlists)
                                .filter(p => !p.isAutoGenerated && p.id !== activePlaylistId)
                                .map(playlist => (
                                    <button
                                        key={playlist.id}
                                        onClick={() => { addSongToPlaylist(playlist.id, playlistModalSongId); setPlaylistModalSongId(null); }}
                                        className="w-full text-left px-4 py-3 rounded-xl bg-white/3 hover:bg-white/5 transition-colors text-zinc-300 font-medium border border-white/5"
                                    >
                                        {playlist.name}
                                    </button>
                                ))}
                            {Object.values(playlists).filter(p => !p.isAutoGenerated && p.id !== activePlaylistId).length === 0 && (
                                <p className="text-zinc-500 text-sm text-center py-4">No custom playlists available.</p>
                            )}
                        </div>
                        <button onClick={() => setPlaylistModalSongId(null)} className="w-full mt-4 py-3 rounded-xl bg-white/5 hover:bg-white/10 text-white font-bold transition-colors">
                            Cancel
                        </button>
                    </div>
                </div>
            )}
        </PageTransition>
    );
};

export default Playlists;
