import React, { useState } from 'react';
import { ListPlus, Plus, X } from 'lucide-react';
import { useLibraryStore } from '../../store/libraryStore';

interface AddToPlaylistModalProps {
    songId: string;
    onClose: () => void;
}

const AddToPlaylistModal: React.FC<AddToPlaylistModalProps> = ({ songId, onClose }) => {
    const { playlists, addSongToPlaylist, createPlaylist } = useLibraryStore();
    const [showCreate, setShowCreate] = useState(false);
    const [newName, setNewName] = useState('');

    const userPlaylists = Object.values(playlists).filter(p => !p.isAutoGenerated);

    const handleAdd = (playlistId: string) => {
        addSongToPlaylist(playlistId, songId);
        onClose();
    };

    const handleCreate = (e: React.FormEvent) => {
        e.preventDefault();
        if (newName.trim()) {
            createPlaylist(newName.trim());
            setNewName('');
            setShowCreate(false);
        }
    };

    return (
        <div
            className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/80 backdrop-blur-xl animate-in fade-in duration-300"
            onClick={onClose}
        >
            <div
                className="bg-surface/90 backdrop-blur-3xl sm:border border-white/10 rounded-t-[40px] sm:rounded-3xl p-8 w-full max-w-md shadow-2xl relative overflow-hidden"
                onClick={e => e.stopPropagation()}
            >
                {/* Top accent line */}
                <div className="absolute top-0 left-0 w-full h-1 bg-linear-to-r from-transparent via-accent to-transparent opacity-50" />
                <div className="w-12 h-1.5 bg-white/10 rounded-full mx-auto mb-6 sm:hidden" />

                <div className="flex items-center justify-between mb-6">
                    <h3 className="text-lg font-black text-white font-['Outfit'] tracking-tight flex items-center gap-2">
                        <ListPlus size={20} className="text-accent" />
                        Add to Playlist
                    </h3>
                    <button onClick={onClose} className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-white/40 hover:text-white hover:bg-white/10 transition-all">
                        <X size={16} />
                    </button>
                </div>

                {/* Playlist list */}
                <div className="space-y-2.5 max-h-[35dvh] overflow-y-auto mb-6 pr-1 scrollbar-hide overscroll-contain">
                    {userPlaylists.length === 0 && !showCreate && (
                        <p className="text-white/30 text-sm text-center py-4">No playlists yet. Create one below.</p>
                    )}
                    {userPlaylists.map(playlist => {
                        const alreadyAdded = playlist.songIds.includes(songId);
                        return (
                            <button
                                key={playlist.id}
                                onClick={() => !alreadyAdded && handleAdd(playlist.id)}
                                disabled={alreadyAdded}
                                className={`w-full text-left px-5 py-4 rounded-2xl transition-all text-white font-semibold border flex items-center justify-between group ${alreadyAdded
                                        ? 'bg-accent/5 border-accent/10 opacity-50 cursor-default'
                                        : 'bg-white/3 border-white/5 hover:bg-accent/5 active:scale-95'
                                    }`}
                            >
                                <span className={alreadyAdded ? 'text-accent/60' : 'group-hover:text-accent transition-colors'}>
                                    {playlist.name}
                                </span>
                                <span className="text-white/20 text-[10px] uppercase font-black tracking-widest">
                                    {alreadyAdded ? 'Added' : `${playlist.songIds.length} tracks`}
                                </span>
                            </button>
                        );
                    })}
                </div>

                {/* Create new playlist */}
                {showCreate ? (
                    <form onSubmit={handleCreate} className="flex gap-2 mb-4">
                        <input
                            type="text"
                            value={newName}
                            onChange={e => setNewName(e.target.value)}
                            placeholder="Playlist name..."
                            autoFocus
                            className="flex-1 px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white text-sm placeholder-white/30 outline-none focus:border-accent/40 transition-colors"
                        />
                        <button
                            type="submit"
                            disabled={!newName.trim()}
                            className="px-4 py-3 rounded-xl bg-accent/10 text-accent font-bold text-sm border border-accent/20 hover:bg-accent/20 transition-all disabled:opacity-30"
                        >
                            Create
                        </button>
                    </form>
                ) : (
                    <button
                        onClick={() => setShowCreate(true)}
                        className="w-full py-4 rounded-2xl bg-white/3 hover:bg-accent/5 text-white/50 hover:text-accent font-bold text-xs uppercase tracking-widest transition-all border border-white/5 hover:border-accent/20 flex items-center justify-center gap-2 mb-4"
                    >
                        <Plus size={14} /> New Playlist
                    </button>
                )}

                {/* Dismiss */}
                <button
                    onClick={onClose}
                    className="w-full py-4 rounded-2xl bg-white/5 hover:bg-red-500/10 hover:text-red-400 text-white/40 font-black uppercase tracking-widest text-xs transition-all border border-transparent hover:border-red-500/20"
                >
                    Cancel
                </button>
            </div>
        </div>
    );
};

export default AddToPlaylistModal;
